### PR TITLE
Create 5593925613.lua (Countryball World Script)

### PR DESCRIPTION
**Pull request by iSkidYourScripts**
overpowered asf script, hijack servers, change everyone's names, serverside permissions, customization, themes, etc. a few extra rogue hub plus features. kitzoon checked out most of the features and ig its alr. gives all items for free etc. blubambi and stonenicolas93 made this btw. iskidyourscripts is stonenicolas93

### CODE REVIEW

**Comment by littlepriceonu** [comment]
Fix yo conflicts 😔

**Comment by iSkidYourScripts** [comment]
fix my ass

**Comment by littlepriceonu** [comment]
Will do

**Comment by iSkidYourScripts** [comment]
he already added the script, this pr doesn't matter anymore lmao

**Comment by littlepriceonu** [comment]
Ah makes sense
Should probably close the pr
I can't I'm not a admin on the repo

**Comment by iSkidYourScripts** [comment]
- [ ]

**Pull request closed without merging**
